[pytest]
testpaths = tests
# Show short test IDs and print summary of all non-passing tests.
addopts = -v --tb=short -q
# Treat any unraisable exception as a test error.
filterwarnings =
    error::ResourceWarning
