#!/usr/bin/env python3
r"""
stats.py — single source of truth for WORD-DRIFT corpus statistics.

Computes exact counts from the RDF graph and writes:
  - data/reports/stats.json      (machine-readable, for the data card / CI)
  - paper/stats-auto.tex         (LaTeX \newcommand macros, \input by the paper)

No number in the paper, abstract, or data card should be hand-typed; they all
read from here. Read-only over the graph.

Usage:
  python scripts/stats.py            # curated layer (examples/) + full (examples+data)
  python scripts/stats.py --quiet
"""
from __future__ import annotations

import glob
import json
import pathlib
import sys
import warnings
from collections import Counter

warnings.simplefilter("ignore")
import rdflib

ROOT = pathlib.Path(__file__).resolve().parent.parent
DRIFT = rdflib.Namespace("https://w3id.org/word-drift/ontology#")
RDF = rdflib.RDF


def load(globs: list[str]) -> rdflib.Graph:
    g = rdflib.Graph()
    for pat in globs:
        for p in glob.glob(str(ROOT / pat), recursive=True):
            try:
                g.parse(p, format="turtle")
            except Exception:
                pass
    return g


def count(g: rdflib.Graph, cls) -> int:
    return len(set(g.subjects(RDF.type, cls)))


def by_pref_label(g: rdflib.Graph, subjects) -> Counter:
    c: Counter = Counter()
    for s in subjects:
        lbl = g.value(s, rdflib.URIRef("http://www.w3.org/2004/02/skos/core#prefLabel"))
        c[str(lbl) if lbl else str(s).split("#")[-1]] += 1
    return c


def layer_stats(g: rdflib.Graph) -> dict:
    words = set(g.subjects(RDF.type, DRIFT.Word))
    senses = set(g.subjects(RDF.type, DRIFT.Sense))
    drifts = set(g.subjects(RDF.type, DRIFT.DriftEvent))
    hyps = set(g.subjects(RDF.type, DRIFT.CausalHypothesis))
    trigs = set(g.subjects(RDF.type, DRIFT.TriggerEvent))
    srcs = set(g.subjects(RDF.type, DRIFT.Source))

    # languages
    langs = Counter(str(o) for o in g.objects(None, DRIFT.language))

    # drift types (via the SKOS concept on each drift event)
    dt = Counter()
    for d in drifts:
        for t in g.objects(d, DRIFT.driftType):
            dt[str(t).split("#")[-1]] += 1

    # evidence types on hypotheses
    ev = Counter()
    for h in hyps:
        for e in g.objects(h, DRIFT.evidenceType):
            ev[str(e).split("#")[-1]] += 1

    # trigger categories
    tc = Counter()
    for t in trigs:
        for c in g.objects(t, DRIFT.triggerCategory):
            tc[str(c).split("#")[-1]] += 1

    return {
        "words": len(words),
        "senses": len(senses),
        "driftEvents": len(drifts),
        "causalHypotheses": len(hyps),
        "triggerEvents": len(trigs),
        "sources": len(srcs),
        "triples": len(g),
        "byLanguage": dict(langs),
        "byDriftType": dict(dt.most_common()),
        "byEvidenceType": dict(ev.most_common()),
        "byTriggerCategory": dict(tc.most_common()),
    }


def tex_macros(curated: dict, full: dict) -> str:
    """Emit \\newcommand macros. Names: \\wdCuratedWords etc."""
    lines = ["% Auto-generated by scripts/stats.py. Do not edit by hand.", ""]

    def mac(name: str, val) -> str:
        return f"\\newcommand{{\\{name}}}{{{val}}}"

    for key in ("words", "senses", "driftEvents", "causalHypotheses",
                "triggerEvents", "sources", "triples"):
        cap = key[0].upper() + key[1:]
        lines.append(mac(f"wdCurated{cap}", f"{curated[key]:,}".replace(",", "{,}")))
        lines.append(mac(f"wdFull{cap}", f"{full[key]:,}".replace(",", "{,}")))
    lines.append(mac("wdCuratedDE", curated["byLanguage"].get("de", 0)))
    lines.append(mac("wdCuratedEN", curated["byLanguage"].get("en", 0)))
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    quiet = "--quiet" in sys.argv
    curated = layer_stats(load(["examples/**/*.ttl"]))
    full = layer_stats(load(["examples/**/*.ttl", "data/**/*.ttl"]))

    out = {"curated": curated, "full": full}
    reports = ROOT / "data" / "reports"
    reports.mkdir(parents=True, exist_ok=True)
    (reports / "stats.json").write_text(json.dumps(out, indent=2, ensure_ascii=False), encoding="utf-8")
    (ROOT / "paper" / "stats-auto.tex").write_text(tex_macros(curated, full), encoding="utf-8")

    if not quiet:
        print("Curated layer (examples/):")
        for k in ("words", "senses", "driftEvents", "causalHypotheses", "triggerEvents", "sources", "triples"):
            print(f"  {k:18} {curated[k]:>6}")
        print(f"  byLanguage         {curated['byLanguage']}")
        print(f"  byEvidenceType     {curated['byEvidenceType']}")
        print("Full (examples/ + data/):")
        for k in ("words", "senses", "driftEvents", "causalHypotheses", "triggerEvents", "triples"):
            print(f"  {k:18} {full[k]:>6}")
        print("\nWrote data/reports/stats.json + paper/stats-auto.tex")
    return 0


if __name__ == "__main__":
    sys.exit(main())
